import type React from "react";
import { FormEvent, useEffect, useState } from "react";

type Review = { name:string; avatar:string; rating:number; date:string; text:string; published:boolean };
type Screenshot = { src:string; alt:string };
type Feature = { icon:string; text:string; enabled:boolean };
type SafetyItem = { icon:string; title:string; desc:string; enabled:boolean };
type SimilarApp = { name:string; icon:string; rating:number; category:string; url:string; enabled:boolean };
type SocialLink = { platform:string; url:string; icon:string; text:string; enabled:boolean };
type ButtonConfig = { text:string; url:string; enabled:boolean; newTab:boolean };
type SiteConfig = {
  app:{name:string; developer:string; category:string; version:string; size:string; downloads:string; ageRating:string; rating:number; totalReviews:number; updateDate:string; compatibility:string; shortDescription:string; description:string};
  logo:string; banner:string; screenshots:Screenshot[]; tags:string[]; features:Feature[]; reviews:Review[];
  ratingDistribution:{5:number;4:number;3:number;2:number;1:number}; safetyIntro:string; safety:SafetyItem[]; similarApps:SimilarApp[];
  social:SocialLink[]; buttons:{download:ButtonConfig; telegram:ButtonConfig}; sections:Record<string,boolean>; footer:{copyright:string; columns:string};
  seo:{title:string; description:string; keywords:string; canonical:string; ogImage:string}; appearance:{primary:string; primaryHover:string; background:string};
};

const DEFAULT:SiteConfig = {
 app:{name:"StreamVibe",developer:"StreamVibe Dev",category:"Entertainment",version:"2.5.1",size:"28.4 MB",downloads:"10,000,000+",ageRating:"PEGI 12",rating:4.5,totalReviews:24583,updateDate:"Dec 15, 2024",compatibility:"Android 5.0+",shortDescription:"Your ultimate entertainment companion.",description:`StreamVibe is your ultimate entertainment companion, bringing you unlimited access to thousands of movies, TV shows, documentaries, and exclusive content — all completely free!\n\nWith StreamVibe, you can explore a vast library of content across multiple genres including Action, Comedy, Drama, Sci-Fi, Horror, Romance, and many more. Our intelligent recommendation engine learns your preferences and suggests content you'll love.\n\nKey highlights include HD and 4K streaming quality, subtitle support in 50+ languages, offline downloads, Chromecast support, and a beautiful dark mode interface that's easy on the eyes.`},
 logo:"/images/logo.webp",banner:"/images/banner.webp",
 screenshots:[1,2,3,4].map((n)=>({src:`/images/screenshot${n}.jpg`,alt:["Home Feed Screen","Content Detail Screen","Search Screen","Profile Screen"][n-1]})),
 tags:["Entertainment","Streaming","Movies & TV","Video Player","Free Content"],
 features:["🎬|Unlimited Movies & TV Shows","📺|HD & 4K Streaming Quality","🌐|Subtitles in 50+ Languages","📥|Offline Downloads","🔄|Daily Content Updates","🌙|Dark Mode Interface","📱|Chromecast Support","⚡|Lightweight & Fast"].map(x=>{const [icon,text]=x.split("|");return {icon,text,enabled:true}}),
 reviews:[
  ["Alex Thompson","AT",5,"December 10, 2024","Absolutely amazing app! The streaming quality is incredible and I love the dark mode. Content library is huge and updates daily. Best free streaming app I've ever used."],
  ["Sarah Mitchell","SM",4,"December 8, 2024","Great app with a fantastic selection of movies and shows. The offline download feature is a lifesaver for my commute. Only wish the search was a bit faster."],
  ["David Chen","DC",5,"December 5, 2024","This app is a game changer! No ads, smooth playback, and the Chromecast support works flawlessly. Recommended to all my friends."],
  ["Maria Garcia","MG",4,"November 29, 2024","Really enjoy using StreamVibe. The subtitle support is great for watching foreign films. Interface is clean and easy to navigate."],
  ["James Wilson","JW",5,"November 22, 2024","Been using this for 3 months now and it just keeps getting better. Zero buffering issues on my connection."]
 ].map(([name,avatar,rating,date,text])=>({name,avatar,rating:Number(rating),date,text,published:true})),
 ratingDistribution:{5:62,4:23,3:9,2:4,1:2},
 safetyIntro:"Safety starts with understanding how developers collect and share your data. Data privacy and security practices may vary based on your use, region, and age.",
 safety:["🔒|Data encrypted in transit|Your data is securely encrypted using TLS 1.3 during transmission.","🛡️|Data can't be deleted|The developer doesn't provide a way to request deletion of your data.","📊|Data shared with third parties|This app may share certain data types with third parties for analytics.","📦|Data collected|App activity, device info, and approximate location may be collected.","✅|Independent security review|This app has been independently reviewed for security compliance."].map(x=>{const [icon,title,desc]=x.split("|");return {icon,title,desc,enabled:true}}),
 similarApps:["MusicStream Pro|/images/app1.webp|4.3|Music & Audio","VidCast Player|/images/app2.webp|4.1|Video Players","DownSync Manager|/images/app3.webp|4.6|Download Manager","MovieHub Free|/images/app1.webp|4.0|Entertainment","ShowTime Plus|/images/app2.webp|4.4|Entertainment","CastFlow TV|/images/app3.webp|3.9|Media & Video"].map(x=>{const [name,icon,rating,category]=x.split("|");return {name,icon,rating:Number(rating),category,url:"#",enabled:true}}),
 social:[{platform:"Telegram",url:"https://t.me/streamvibeofficial",icon:"✈️",text:"Join Telegram",enabled:true}],
 buttons:{download:{text:"Download APK",url:"https://example.com/streamvibe-v2.5.apk",enabled:true,newTab:true},telegram:{text:"Join Telegram",url:"https://t.me/streamvibeofficial",enabled:true,newTab:true}},
 sections:{banner:true,appInfo:true,tags:true,screenshots:true,description:true,features:true,reviews:true,ratings:true,safety:true,similarApps:true,social:true,sticky:true},
 footer:{copyright:"All rights reserved. Independent app listing and download page.",columns:"About|Privacy|Terms|Support|Contact|Developer information"},
 seo:{title:"StreamVibe - Download APK",description:"Download the latest StreamVibe APK.",keywords:"apk download, android games, mod apk",canonical:"",ogImage:""},
 appearance:{primary:"#01875f",primaryHover:"#016e4f",background:"#ffffff"}
};

const KEY="streamvibe-admin-config-v2";
const AUTH="streamvibe-admin-auth";
function loadConfig():SiteConfig{try{return {...DEFAULT,...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch{return DEFAULT}}
function saveConfig(c:SiteConfig){localStorage.setItem(KEY,JSON.stringify(c));}
function LazyImage({src,alt,className="",priority=false}:{src:string;alt:string;className?:string;priority?:boolean}){return <img src={src} alt={alt} className={className} loading={priority?"eager":"lazy"} fetchPriority={priority?"high":"auto"} decoding="async" onError={(e)=>{(e.currentTarget as HTMLImageElement).style.opacity=".35"}}/>}
function Stars({rating}:{rating:number}){return <span className="stars">{[1,2,3,4,5].map(s=><span key={s}>{s<=Math.round(rating)?"★":"☆"}</span>)}</span>}
function Field({label,value,onChange,type="text",placeholder}:{label:string;value:any;onChange:(v:any)=>void;type?:string;placeholder?:string}){return <label className="field"><span>{label}</span><input type={type} value={value ?? ""} placeholder={placeholder} onChange={e=>onChange(type==="number"?Number(e.target.value):e.target.value)}/></label>}
function TextArea({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="field"><span>{label}</span><textarea value={value} onChange={e=>onChange(e.target.value)} /></label>}
function Toggle({label,value,onChange}:{label:string;value:boolean;onChange:(v:boolean)=>void}){return <label className="toggle"><input type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)}/><span>{label}</span></label>}
function ImageField({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){const [upload,setUpload]=useState(false);const file=(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;if(f.size>2*1024*1024){alert("Image must be under 2 MB");return}const r=new FileReader();r.onload=()=>onChange(String(r.result));r.readAsDataURL(f)};return <div className="image-field"><Field label={label+" URL"} value={value} onChange={onChange} placeholder="https://... or /images/file.jpg"/><button type="button" className="secondary" onClick={()=>setUpload(!upload)}>{upload?"Hide uploader":"Upload image"}</button>{upload&&<input className="file" type="file" accept="image/*" onChange={file}/>} {value&&<img className="preview" src={value} alt="preview"/>}</div>}

function PublicSite({config}:{config:SiteConfig}){
 const a=config.app; const [expanded,setExpanded]=useState(false); const [safetyExpanded,setSafetyExpanded]=useState(false); const [sticky,setSticky]=useState(false);
 useEffect(()=>{const f=()=>setSticky(scrollY>400);addEventListener("scroll",f);return()=>removeEventListener("scroll",f)},[]);
 useEffect(()=>{document.title=config.seo.title||a.name;document.documentElement.style.setProperty("--primary",config.appearance.primary);document.documentElement.style.setProperty("--primary-hover",config.appearance.primaryHover)},[config]);
 const socials=config.social.filter(x=>x.enabled); const reviews=config.reviews.filter(x=>x.published); const safety=config.safety.filter(x=>x.enabled); const features=config.features.filter(x=>x.enabled); const similar=config.similarApps.filter(x=>x.enabled);
 return <div className="site" style={{background:config.appearance.background}}><nav className="topbar"><div className="container"><div className="brand-mark" aria-label="AppNest">◆</div><span className="brand-name">AppNest</span><span className="brand-subtitle">App Store</span></div></nav>
 <main>
 {config.sections.appInfo&&<section><div className="container header"><LazyImage src={config.logo} alt={`${a.name} logo`} className="app-logo" priority/><div className="head-copy"><h1>{a.name}</h1><p className="developer">{a.developer}</p><div className="meta"><b>{a.rating}</b> <Stars rating={a.rating}/> <span>({a.totalReviews.toLocaleString()} reviews)</span><i>•</i><span>{a.downloads} downloads</span><i>•</i><span>{a.ageRating}</span></div></div></div><div className="container pills"><span>⇩ {a.size}</span><span>▦ {a.category}</span><span>◷ v{a.version}</span></div></section>}
 {config.sections.banner&&<section><div className="container hero"><LazyImage src={config.banner} alt={`${a.name} banner`} className="banner" priority/><div className="actions">{config.buttons.download.enabled&&<a className="btn primary" href={config.buttons.download.url} target={config.buttons.download.newTab?"_blank":undefined} rel="noreferrer">⇩ {config.buttons.download.text}</a>}{config.buttons.telegram.enabled&&<a className="btn telegram" href={config.buttons.telegram.url} target={config.buttons.telegram.newTab?"_blank":undefined} rel="noreferrer">✈ {config.buttons.telegram.text}</a>}</div>{socials.length>0&&config.sections.social&&<div className="social-row">{socials.map((s,i)=><a key={i} href={s.url} target="_blank" rel="noreferrer">{s.icon} {s.text||s.platform}</a>)}</div>}</div></section>}
 {config.sections.tags&&<section><div className="container tags">{config.tags.map((t,i)=><span key={i}>{t}</span>)}</div></section>}
 {config.sections.screenshots&&<section><div className="container"><h2>Screenshots</h2><div className="screens">{config.screenshots.map((s,i)=><LazyImage key={i} src={s.src} alt={s.alt} className="shot"/>)}</div></div></section>}
 {config.sections.description&&<section><div className="container"><h2>About this app</h2><p className={`description ${expanded?"expanded":""}`}>{a.description}</p><button className="text-btn" onClick={()=>setExpanded(!expanded)}>{expanded?"Show less":"Show more"}</button>{config.sections.features&&<><h3>Features</h3><div className="features">{features.map((f,i)=><span key={i}>{f.icon} {f.text}</span>)}</div></>}<div className="info-grid"><div>Version<strong>{a.version}</strong></div><div>Size<strong>{a.size}</strong></div><div>Updated on<strong>{a.updateDate}</strong></div><div>Requires Android<strong>{a.compatibility}</strong></div></div></div></section>}
 {config.sections.ratings&&<section><div className="container"><h2>Ratings and reviews</h2><div className="rating-box"><div><strong className="big-rating">{a.rating}</strong><Stars rating={a.rating}/><small>{a.totalReviews.toLocaleString()} reviews</small></div><div className="bars">{[5,4,3,2,1].map(s=><div className="bar-row" key={s}><span>{s}</span><div><i style={{width:`${config.ratingDistribution[s as 1|2|3|4|5]}%`}}/></div><small>{config.ratingDistribution[s as 1|2|3|4|5]}%</small></div>)}</div></div>{config.sections.reviews&&<div className="reviews">{reviews.map((r,i)=><article key={i}><div className="avatar">{r.avatar}</div><div><div className="review-head"><b>{r.name}</b><small>{r.date}</small></div><Stars rating={r.rating}/><p>{r.text}</p></div></article>)}</div>}</div></section>}
 {config.sections.safety&&<section><div className="container"><h2>Data safety</h2><p className="muted">{config.safetyIntro}</p>{(safetyExpanded?safety:safety.slice(0,3)).map((x,i)=><div className="safety" key={i}><span>{x.icon}</span><div><b>{x.title}</b><p>{x.desc}</p></div></div>)}{safety.length>3&&<button className="text-btn" onClick={()=>setSafetyExpanded(!safetyExpanded)}>{safetyExpanded?"Show less":"Show more"}</button>}</div></section>}
 {config.sections.similarApps&&<section><div className="container"><h2>Similar apps</h2><div className="similar">{similar.map((x,i)=><a href={x.url} key={i}><LazyImage src={x.icon} alt={x.name}/><b>{x.name}</b><span>{x.rating} ★</span><small>{x.category}</small></a>)}</div></div></section>}
 </main><footer><div className="container"><div className="footer-grid">{config.footer.columns.split("|").map((x,i)=><span key={i}>{x}</span>)}</div><p>© 2024 {a.developer}. {config.footer.copyright}</p></div></footer>
 {config.sections.sticky&&<div className={`sticky ${sticky?"show":""}`}><div><img src={config.logo} alt=""/><b>{a.name}</b></div>{config.buttons.download.enabled&&<a className="btn primary" href={config.buttons.download.url}>Install</a>}</div>}
 </div>
}

function Admin({config,setConfig,onLogout}:{config:SiteConfig;setConfig:(c:SiteConfig)=>void;onLogout:()=>void}){
 const [tab,setTab]=useState("Dashboard"); const [draft,setDraft]=useState<SiteConfig>(config); const [saved,setSaved]=useState(false);
 useEffect(()=>setDraft(config),[config]); const update=(fn:(c:SiteConfig)=>void)=>setDraft(c=>{const n=structuredClone(c);fn(n);return n});
 const save=()=>{setConfig(draft);setSaved(true);setTimeout(()=>setSaved(false),1600)};
 const reset=()=>{if(confirm("Reset all site settings to the original content?")){setDraft(structuredClone(DEFAULT));save()}};
 const exportData=()=>{const blob=new Blob([JSON.stringify(draft,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="site-config.json";a.click();URL.revokeObjectURL(a.href)};
 const importData=(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{setDraft(JSON.parse(String(r.result)));alert("Configuration imported. Click Save All Changes.")}catch{alert("Invalid JSON file")}};r.readAsText(f)};
 const nav=["Dashboard","App Information","Images & Media","Download & Social","Description & Features","Screenshots","Reviews & Ratings","Data Safety","Similar Apps","Sections","SEO & Appearance","Footer","Admin Account"];
 const Section=({title,children}:{title:string;children:React.ReactNode})=><div className="admin-card"><h2>{title}</h2>{children}</div>;
 const add=(key:keyof SiteConfig,item:any)=>update(c=>(c[key] as any).push(item));
 return <div className="admin-shell"><aside><div className="brand">⚙️ Site Admin</div>{nav.map(n=><button key={n} className={tab===n?"active":""} onClick={()=>setTab(n)}>{n}</button>)}<button onClick={()=>window.open("/","_blank")}>↗ Preview Site</button><button onClick={exportData}>⇩ Export Config</button><label className="import-btn">⇧ Import Config<input type="file" accept="application/json" onChange={importData}/></label><button onClick={onLogout}>Logout</button></aside><div className="admin-main"><header><div><h1>{tab}</h1><p>Manage your landing page without editing code.</p></div><div className="head-actions"><button className="secondary" onClick={reset}>Reset</button><button className="save" onClick={save}>✓ Save All Changes</button></div></header>{saved&&<div className="toast">Saved successfully</div>}
 {tab==="Dashboard"&&<><Section title="Overview"><div className="stats">{[["App name",draft.app.name],["Screenshots",draft.screenshots.length],["Features",draft.features.length],["Reviews",draft.reviews.length],["Similar apps",draft.similarApps.length],["APK URL",draft.buttons.download.url?"Configured":"Missing"]].map(([k,v])=><div className="stat" key={String(k)}><small>{k}</small><b>{v}</b></div>)}</div></Section><Section title="Quick actions"><div className="quick"><button onClick={()=>setTab("App Information")}>Edit app information</button><button onClick={()=>setTab("Images & Media")}>Manage images</button><button onClick={()=>setTab("Download & Social")}>Manage URLs & social links</button><button onClick={()=>setTab("Screenshots")}>Manage screenshots</button></div></Section></>}
 {tab==="App Information"&&<Section title="App Information"><div className="form-grid">{Object.entries(draft.app).filter(([k])=>k!=="description").map(([k,v])=><Field key={k} label={k.replace(/([A-Z])/g," $1")} value={v} type={typeof v==="number"?"number":"text"} onChange={x=>update(c=>{(c.app as any)[k]=x})}/>)}</div><TextArea label="Short description" value={draft.app.shortDescription} onChange={x=>update(c=>c.app.shortDescription=x)}/><TextArea label="Full description" value={draft.app.description} onChange={x=>update(c=>c.app.description=x)}/></Section>}
 {tab==="Images & Media"&&<><Section title="Brand images"><div className="two"><ImageField label="App logo" value={draft.logo} onChange={x=>update(c=>c.logo=x)}/><ImageField label="Banner" value={draft.banner} onChange={x=>update(c=>c.banner=x)}/></div></Section><Section title="Upload notes"><p className="muted">You can paste any public image URL or upload an image. Uploaded images are stored in this browser's configuration as data URLs, so keep them under 2 MB each. For multi-device production storage, connect a backend such as Supabase later.</p></Section></>}
 {tab==="Download & Social"&&<><Section title="Download buttons"><div className="form-grid"><div><Toggle label="Enable download button" value={draft.buttons.download.enabled} onChange={x=>update(c=>c.buttons.download.enabled=x)}/><Field label="Button text" value={draft.buttons.download.text} onChange={x=>update(c=>c.buttons.download.text=x)}/><Field label="APK / download URL" value={draft.buttons.download.url} onChange={x=>update(c=>c.buttons.download.url=x)}/><Toggle label="Open in new tab" value={draft.buttons.download.newTab} onChange={x=>update(c=>c.buttons.download.newTab=x)}/></div><div><Toggle label="Enable Telegram button" value={draft.buttons.telegram.enabled} onChange={x=>update(c=>c.buttons.telegram.enabled=x)}/><Field label="Button text" value={draft.buttons.telegram.text} onChange={x=>update(c=>c.buttons.telegram.text=x)}/><Field label="Telegram URL" value={draft.buttons.telegram.url} onChange={x=>update(c=>c.buttons.telegram.url=x)}/><Toggle label="Open in new tab" value={draft.buttons.telegram.newTab} onChange={x=>update(c=>c.buttons.telegram.newTab=x)}/></div></div></Section><Section title="Social links"><div className="list-editor">{draft.social.map((s,i)=><div className="list-row" key={i}><Field label="Platform" value={s.platform} onChange={x=>update(c=>c.social[i].platform=x)}/><Field label="URL" value={s.url} onChange={x=>update(c=>c.social[i].url=x)}/><Field label="Icon" value={s.icon} onChange={x=>update(c=>c.social[i].icon=x)}/><Field label="Button text" value={s.text} onChange={x=>update(c=>c.social[i].text=x)}/><Toggle label="Enabled" value={s.enabled} onChange={x=>update(c=>c.social[i].enabled=x)}/><button className="danger" onClick={()=>update(c=>c.social.splice(i,1))}>Delete</button></div>)}</div><button className="secondary" onClick={()=>add("social",{platform:"Custom",url:"https://",icon:"🔗",text:"Visit",enabled:true})}>+ Add social link</button></Section></>}
 {tab==="Description & Features"&&<><Section title="Description"><TextArea label="About this app" value={draft.app.description} onChange={x=>update(c=>c.app.description=x)}/><TextArea label="Safety / extra description" value={draft.safetyIntro} onChange={x=>update(c=>c.safetyIntro=x)}/></Section><Section title="Category tags"><div className="chips-edit">{draft.tags.map((t,i)=><div key={i}><input value={t} onChange={e=>update(c=>c.tags[i]=e.target.value)}/><button onClick={()=>update(c=>c.tags.splice(i,1))}>×</button></div>)}</div><button className="secondary" onClick={()=>update(c=>c.tags.push("New Tag"))}>+ Add tag</button></Section><Section title="Features"><div className="list-editor">{draft.features.map((f,i)=><div className="list-row" key={i}><Field label="Icon" value={f.icon} onChange={x=>update(c=>c.features[i].icon=x)}/><Field label="Feature text" value={f.text} onChange={x=>update(c=>c.features[i].text=x)}/><Toggle label="Enabled" value={f.enabled} onChange={x=>update(c=>c.features[i].enabled=x)}/><button className="danger" onClick={()=>update(c=>c.features.splice(i,1))}>Delete</button></div>)}</div><button className="secondary" onClick={()=>add("features",{icon:"✨",text:"New feature",enabled:true})}>+ Add feature</button></Section></>}
 {tab==="Screenshots"&&<Section title="Screenshot manager"><div className="list-editor">{draft.screenshots.map((s,i)=><div className="list-row media-row" key={i}><ImageField label={`Screenshot ${i+1}`} value={s.src} onChange={x=>update(c=>c.screenshots[i].src=x)}/><Field label="Alt text" value={s.alt} onChange={x=>update(c=>c.screenshots[i].alt=x)}/><button className="danger" onClick={()=>update(c=>c.screenshots.splice(i,1))}>Delete</button></div>)}</div><button className="secondary" onClick={()=>add("screenshots",{src:"/images/screenshot1.webp",alt:"New screenshot"})}>+ Add screenshot</button></Section>}
 {tab==="Reviews & Ratings"&&<><Section title="Rating distribution"><div className="form-grid">{[5,4,3,2,1].map(s=><Field key={s} label={`${s}-star percentage`} value={draft.ratingDistribution[s as 1|2|3|4|5]} type="number" onChange={x=>update(c=>(c.ratingDistribution as any)[s]=x)}/>)}</div></Section><Section title="Reviews"><div className="list-editor">{draft.reviews.map((r,i)=><div className="list-row" key={i}><Field label="Name" value={r.name} onChange={x=>update(c=>c.reviews[i].name=x)}/><Field label="Avatar" value={r.avatar} onChange={x=>update(c=>c.reviews[i].avatar=x)}/><Field label="Rating" value={r.rating} type="number" onChange={x=>update(c=>c.reviews[i].rating=x)}/><Field label="Date" value={r.date} onChange={x=>update(c=>c.reviews[i].date=x)}/><TextArea label="Review" value={r.text} onChange={x=>update(c=>c.reviews[i].text=x)}/><Toggle label="Published" value={r.published} onChange={x=>update(c=>c.reviews[i].published=x)}/><button className="danger" onClick={()=>update(c=>c.reviews.splice(i,1))}>Delete</button></div>)}</div><button className="secondary" onClick={()=>add("reviews",{name:"New Reviewer",avatar:"NR",rating:5,date:new Date().toLocaleDateString(),text:"Write review here...",published:true})}>+ Add review</button></Section></>}
 {tab==="Data Safety"&&<Section title="Data safety"><TextArea label="Intro text" value={draft.safetyIntro} onChange={x=>update(c=>c.safetyIntro=x)}/><div className="list-editor">{draft.safety.map((s,i)=><div className="list-row" key={i}><Field label="Icon" value={s.icon} onChange={x=>update(c=>c.safety[i].icon=x)}/><Field label="Title" value={s.title} onChange={x=>update(c=>c.safety[i].title=x)}/><TextArea label="Description" value={s.desc} onChange={x=>update(c=>c.safety[i].desc=x)}/><Toggle label="Enabled" value={s.enabled} onChange={x=>update(c=>c.safety[i].enabled=x)}/><button className="danger" onClick={()=>update(c=>c.safety.splice(i,1))}>Delete</button></div>)}</div><button className="secondary" onClick={()=>add("safety",{icon:"🔐",title:"New safety item",desc:"Describe this practice.",enabled:true})}>+ Add safety item</button></Section>}
 {tab==="Similar Apps"&&<Section title="Similar apps"><div className="list-editor">{draft.similarApps.map((s,i)=><div className="list-row media-row" key={i}><ImageField label="Icon" value={s.icon} onChange={x=>update(c=>c.similarApps[i].icon=x)}/><Field label="Name" value={s.name} onChange={x=>update(c=>c.similarApps[i].name=x)}/><Field label="Rating" value={s.rating} type="number" onChange={x=>update(c=>c.similarApps[i].rating=x)}/><Field label="Category" value={s.category} onChange={x=>update(c=>c.similarApps[i].category=x)}/><Field label="Destination URL" value={s.url} onChange={x=>update(c=>c.similarApps[i].url=x)}/><Toggle label="Enabled" value={s.enabled} onChange={x=>update(c=>c.similarApps[i].enabled=x)}/><button className="danger" onClick={()=>update(c=>c.similarApps.splice(i,1))}>Delete</button></div>)}</div><button className="secondary" onClick={()=>add("similarApps",{name:"New App",icon:"/images/app1.webp",rating:4,category:"Entertainment",url:"#",enabled:true})}>+ Add similar app</button></Section>}
 {tab==="Sections"&&<Section title="Section visibility"><div className="section-toggles">{Object.entries(draft.sections).map(([k,v])=><Toggle key={k} label={k.replace(/([A-Z])/g," $1")} value={v} onChange={x=>update(c=>c.sections[k]=x)}/>)}</div></Section>}
 {tab==="SEO & Appearance"&&<><Section title="SEO"><div className="form-grid">{Object.entries(draft.seo).map(([k,v])=><Field key={k} label={k} value={v} onChange={x=>update(c=>(c.seo as any)[k]=x)}/>)}</div></Section><Section title="Appearance"><div className="form-grid"><Field label="Primary color" value={draft.appearance.primary} onChange={x=>update(c=>c.appearance.primary=x)}/><Field label="Primary hover" value={draft.appearance.primaryHover} onChange={x=>update(c=>c.appearance.primaryHover=x)}/><Field label="Page background" value={draft.appearance.background} onChange={x=>update(c=>c.appearance.background=x)}/></div></Section></>}
 {tab==="Footer"&&<Section title="Footer"><TextArea label="Copyright / disclaimer text" value={draft.footer.copyright} onChange={x=>update(c=>c.footer.copyright=x)}/><TextArea label="Footer items (separate with |)" value={draft.footer.columns} onChange={x=>update(c=>c.footer.columns=x)}/></Section>}
 {tab==="Admin Account"&&<AdminAccount/>}
 </div></div>
}
function AdminAccount(){const [p,setP]=useState("");const save=()=>{if(p.length<6)return alert("Use at least 6 characters");localStorage.setItem("streamvibe-admin-password",p);setP("");alert("Password updated")};return <div className="admin-card"><h2>Change admin password</h2><p className="muted">This static version stores the admin password in your browser. It is suitable for a personal/local admin workflow, not a secure multi-user backend.</p><Field label="New password" value={p} onChange={setP} type="password"/><button className="save" onClick={save}>Update password</button></div>}
function Login({onLogin}:{onLogin:()=>void}){const [p,setP]=useState("");const submit=(e:FormEvent)=>{e.preventDefault();const stored=localStorage.getItem("streamvibe-admin-password")||"admin123";if(p===stored){localStorage.setItem(AUTH,"1");onLogin()}else alert("Incorrect password")};return <div className="login"><form onSubmit={submit}><div className="login-logo">⚙️</div><h1>Admin Panel</h1><p>Sign in to manage your landing page.</p><input type="password" placeholder="Admin password" value={p} onChange={e=>setP(e.target.value)} autoFocus/><button className="save">Login</button><small>First login password: <b>admin123</b></small></form></div>}

export default function App(){const [config,setConfigState]=useState<SiteConfig>(loadConfig());const [admin,setAdmin]=useState(()=>location.pathname.startsWith("/admin")&&localStorage.getItem(AUTH)==="1");const isAdmin=location.pathname.startsWith("/admin");const setConfig=(c:SiteConfig)=>{setConfigState(c);saveConfig(c)};if(isAdmin&&!admin)return <Login onLogin={()=>setAdmin(true)}/>;if(isAdmin)return <Admin config={config} setConfig={setConfig} onLogout={()=>{localStorage.removeItem(AUTH);setAdmin(false)}}/>;return <PublicSite config={config}/>}
